; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes='sroa<preserve-cfg>' -S -debug | FileCheck %s --check-prefixes=CHECK,CHECK-PRESERVE-CFG
; RUN: opt < %s -passes='sroa<modify-cfg>' -S | FileCheck %s --check-prefixes=CHECK,CHECK-MODIFY-CFG

%S0 = type { i32, i32, i32, i32 }

define void @test(ptr %in, ptr %out) nounwind uwtable {
entry:
  %s = alloca %S0

  %0 = load i32, ptr %in
  %1 = call ptr (%S0, ptr, ...) @llvm.structured.gep.inbounds(%S0 poison, ptr %s, i32 1)
  store i32 %0, ptr %1

  %2 = call ptr (%S0, ptr, ...) @llvm.structured.gep.inbounds(%S0 poison, ptr %s, i32 1)
  %3 = load i32, ptr %2
  store i32 %3, ptr %out

;  %arr = alloca [2 x i32]
;
;
;  ;%a = getelementptr i8, ptr %s, i64 0
;  ;%c = getelementptr i8, ptr %s, i64 8
;  ;%a = call ptr (%S0, ptr, ...) @llvm.structured.gep.inbounds(%S0 poison, ptr %s, i32 0)
;  ;%c = call ptr (%S0, ptr, ...) @llvm.structured.gep.inbounds(%S0 poison, ptr %s, i32 2)
;
;  %0 = load %S0, ptr %in, align 4
;  store %S0 %0, ptr %s
;
;  ;%b = getelementptr i8, ptr %s, i64 4
;  %b = call ptr (%S0, ptr, ...) @llvm.structured.gep(%S0 poison, ptr %s, i32 1)
;  ;%d = getelementptr i8, ptr %s, i64 12
;  %d = call ptr (%S0, ptr, ...) @llvm.structured.gep(%S0 poison, ptr %s, i32 3)
;
;  %1 = load i32, ptr %b
;  %2 = getelementptr i8, ptr %out, i64 0
;  store i32 %1, ptr %2
;
;  %3 = load i32, ptr %d
;  %4 = getelementptr i8, ptr %out, i64 4
;  store i32 %3, ptr %4

  ret void
}

